default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: first
  password: asdfg
  host: localhost 

development:
  <<: *default
  database: busation_dev 

test:
  <<: *default
  database: busation_test

production:
  <<: *default
  database: busation_prod
